# Generated by Django 3.0.3 on 2020-05-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='docurl',
        ),
    ]
