# Generated by Django 3.0.3 on 2020-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtask',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
